### ISSUE TITLE
Implement mustache pre-/post-processing and directive

### ISSUE THREAD

**Issue by shah** [resFactory/factory#11]
We need to implement [mustache.js](https://github.com/janl/mustache.js), [M4](https://github.com/jeanlauliac/js-m4) or more specifically any really fast _logicless_ template engine for:

* frontmatter/content _pre-_ processor allows processing of front matter before any other Markdown parsing is done
* frontmatter/content _post-_ processor allows updating of front matter after all other Markdown parsing is completed (in case the pre-processing generated additional mustache).
* HTML web component uses [this strategy](https://github.com/janl/mustache.js#include-templates)
* markdown directive wrapping the HTML web component

For frontmatter:

```yaml
.resFactory: 
  preProcess:
    frontmatter: yes
    content: no
  postProcess:
    frontmatter: no
    content: yes
key:
  {{tag}}: {{value}}
key2: 
  {{tag2}}: {{value2}}
{{dynamicKey3}}: 
  {{tag2}}: {{value2}}
```

Frontmatter is allowed in HTML and Markdown files and should be pre-/post-processable to allow dynamic functionality. Markdown is basically just information architecture so allowing it to be dynamic is good.
