### ISSUE TITLE
Influence search, discovery, and navigation behavior using frontmatter

### ISSUE THREAD

**Issue by shah** [resFactory/factory#49]
Add to frontmatter for indexing

```yaml
identity:
  shortened:
      native: /x/ABC
      bit.ly: true | URL        # true gets dynamic, URL is absolute
  symbol: ABC                     # use with [XYZ](${symbol:ABC}) or similar to target via symbol instead of URL
```
