### ISSUE TITLE
Enable symbolic identification and targeting of resources

### ISSUE THREAD

**Issue by shah** [resFactory/factory#51]
Add frontmatter for unique identification and direct targeting:

```yaml
identity: ABC
identity:
  shortened:
      native: /x/ABC
      bit.ly: true | URL        # true gets dynamic, URL is absolute
  symbol: ABC                   # use with [XYZ](${symbol:ABC}) or similar to target via symbol instead of URL
```

This can be implemented using Identifiable interface which can be implemented by those Resources which will support unique, symbolic, identification. Once identified resources can by hyperlinked using `[XYZ](${symbol:ABC})` or similar to target via symbol instead of URL
