### ISSUE TITLE
Add content governance directives

### ISSUE THREAD

**Issue by SonalikaG** [resFactory/factory#56]
We should include content governance directives via frontmatter and other techniques -- like:

```yaml
governance:
  classification: (?)
  retention:
    archive: date
```
